
geoip2 /etc/nginx/geoip/GeoLite2-Country.mmdb {
    $geoip_country_code source=$remote_addr country iso_code;
    $geoip_country_name source=$remote_addr country names en;
}

log_format analytics
  'ip=$remote_addr '
  'xff=$http_x_forwarded_for '
  'time="$time_local" '
  'method=$request_method '
  'uri="$request_uri" '
  'proto=$server_protocol '
  'status=$status '
  'bytes=$body_bytes_sent '
  'ref="$http_referer" '
  'ua="$http_user_agent" '
  'country=$geoip_country_code '
  'country_name="$geoip_country_name" '
  'host=$host '
  'req_time=$request_time';

access_log /var/log/nginx/access_analytics.log analytics;

server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://localhost:3000;
    }
}
